BASE_URL = "https://www.saucedemo.com/"
#LOGIN_URL = f"{BASE_URL}/login"
LOGIN_URL = "https://www.saucedemo.com/"
USERNAME = "standard_user"
PASSWORD = "secret_sauce"
LOCKED_USER = "locked_out_user"
GLITCH_USER = "performance_glitch_user"